_base_: vgm_bridge_multiview_base_53f.yaml
common:
  multiview_mode: "legacy"
  multiview_layout: "horizontal"
  multiview_output_layout: "horizontal"
  video_height: 224
  video_width: 448
dataset:
  view_layout: "horizontal"
logging:
  run_name: "vgm_bridge_mv0_h_rgb_mosaic_53f_2gpu_gbs8_50k"
