#!/usr/bin/env python3
"""Build a focused human-decision pack for unresolved SAM3 mask QA cases."""

from __future__ import annotations

import argparse
import csv
import html
import os
from pathlib import Path
from typing import Dict, List


DEFAULT_RECOMMENDATIONS = {
    "sample_002": {
        "decision": "Check whether the mug/plate masks are sufficient. In v3 refined this needed boxes for mug frame 4 and plate frames 6/15; in v4 draft those zero frames are filled and need visual approval.",
        "default": "Use the v4 draft boxes if the mug/plate masks look visually acceptable; otherwise tighten the boxes around the local mug/plate contact region.",
    },
    "sample_005": {
        "decision": "Approve the drawer target definition.",
        "default": "Use drawer handle/front as target; keep broad cabinet/table boxes as context only.",
    },
    "sample_006": {
        "decision": "Check whether the bowl/cabinet final mask is local enough.",
        "default": "Accept if bowl + robot + local cabinet interaction is the intended emphasis.",
    },
    "sample_009": {
        "decision": "Confirm which visible can is alphabet soup.",
        "default": "Do not approve until the correct object identity is confirmed.",
    },
    "sample_015": {
        "decision": "Check whether black bowl and plate coverage is appropriate.",
        "default": "Accept if bowl + plate + robot contact region should receive higher loss.",
    },
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--review_dir",
        default="artifacts/v3_sam3_mask_review_manual_v3_refined",
        help="Root review directory generated by make_sam3_mask_review_gallery.py.",
    )
    parser.add_argument("--detail_label", default="manual-v3-refined")
    parser.add_argument(
        "--output_html",
        default=None,
        help="Output HTML path. Defaults to <review_dir>/summary/human_decision_pack.html.",
    )
    parser.add_argument(
        "--output_csv",
        default=None,
        help="Output decision CSV path. Defaults to <review_dir>/summary/human_decision_template.csv.",
    )
    return parser.parse_args()


def read_csv_rows(path: Path) -> List[Dict[str, str]]:
    with open(path, "r", encoding="utf-8", newline="") as file:
        return list(csv.DictReader(file))


def rel(path: Path, base: Path) -> str:
    return html.escape(os.path.relpath(path.resolve(), base.resolve().parent))


def sample_id_to_int(sample: str) -> int:
    return int(sample.rsplit("_", 1)[1])


def existing_link(path: Path, label: str, html_path: Path) -> str:
    if not path.exists():
        return f"<span class='missing'>{html.escape(label)} missing</span>"
    return f"<a href='{rel(path, html_path)}'>{html.escape(label)}</a>"


def optional_link(path: Path, label: str, html_path: Path) -> str:
    if not path.exists():
        return ""
    return existing_link(path, label, html_path)


def image_block(path: Path, label: str, html_path: Path) -> str:
    if not path.exists():
        return f"<div class='image-block missing'>{html.escape(label)} missing: {html.escape(str(path))}</div>"
    href = rel(path, html_path)
    return (
        "<figure class='image-block'>"
        f"<figcaption>{html.escape(label)}</figcaption>"
        f"<a href='{href}'><img src='{href}' alt='{html.escape(label)}'></a>"
        "</figure>"
    )


def preview_links(review_dir: Path, sample: str, html_path: Path) -> List[str]:
    links = []
    for preview_dir in sorted(review_dir.glob("manual_override_previews*")):
        if not preview_dir.is_dir():
            continue
        path = preview_dir / f"{sample}_manual_override_preview.png"
        if path.exists():
            label = preview_dir.name.replace("manual_override_previews_", "preview ")
            links.append(existing_link(path, label, html_path))
    return links


def find_sample_file(directory: Path, sample: str, suffix: str) -> Path:
    paths = sorted(directory.glob(f"{sample}_*{suffix}"))
    return paths[0] if paths else directory / f"{sample}_missing{suffix}"


def write_decision_csv(issue_rows: List[Dict[str, str]], output_csv: Path) -> None:
    output_csv.parent.mkdir(parents=True, exist_ok=True)
    fieldnames = [
        "sample",
        "task_text",
        "current_status",
        "issue_frames",
        "reasons",
        "decision_needed",
        "default_recommendation",
        "human_decision",
        "approved_for_larger_validation",
    ]
    existing_by_sample: Dict[str, Dict[str, str]] = {}
    if output_csv.exists():
        with open(output_csv, "r", encoding="utf-8", newline="") as file:
            existing_by_sample = {row.get("sample", ""): row for row in csv.DictReader(file)}

    with open(output_csv, "w", encoding="utf-8", newline="") as file:
        writer = csv.DictWriter(file, fieldnames=fieldnames)
        writer.writeheader()
        for row in issue_rows:
            sample = row["sample"]
            rec = DEFAULT_RECOMMENDATIONS.get(sample, {})
            existing = existing_by_sample.get(sample, {})
            writer.writerow(
                {
                    "sample": sample,
                    "task_text": row.get("task_text", ""),
                    "current_status": row.get("current_status", ""),
                    "issue_frames": row.get("issue_frames", ""),
                    "reasons": row.get("reasons", ""),
                    "decision_needed": rec.get("decision", ""),
                    "default_recommendation": rec.get("default", ""),
                    "human_decision": existing.get("human_decision", ""),
                    "approved_for_larger_validation": existing.get("approved_for_larger_validation", ""),
                }
            )


def write_html(review_dir: Path, issue_rows: List[Dict[str, str]], output_html: Path, detail_label: str) -> None:
    output_html.parent.mkdir(parents=True, exist_ok=True)
    summary_dir = review_dir / "summary"
    compare_label = "auto_vs_manual-v2_vs_manual-v3-draft_vs_manual-v3-refined"

    cards = []
    for row in issue_rows:
        sample = row["sample"]
        sample_num = sample_id_to_int(sample)
        rec = DEFAULT_RECOMMENDATIONS.get(sample, {})
        issue_crop = review_dir / "issue_crops" / detail_label / f"{sample}_{detail_label}_issue_crop_review.png"
        compare = find_sample_file(review_dir / "compare", sample, "_review.png")
        focused = review_dir / "focused" / detail_label / f"{sample}_{detail_label}_focused_review.png"
        top = review_dir / "focused_view_splits" / detail_label / "top" / f"{sample}_{detail_label}_top_view_review.png"
        bottom = review_dir / "focused_view_splits" / detail_label / "bottom" / f"{sample}_{detail_label}_bottom_view_review.png"
        guide = review_dir / "issue_annotation_guides" / f"{sample}_manual_box_guide_issue_frames.png"
        operation_crop = review_dir / "operation_crops" / f"{sample}_operation_crop_review.png"
        identity_aid = review_dir / "identity_decision_aids" / f"{sample}_identity_decision_aid.png"

        link_items = (
            [
                existing_link(issue_crop, "issue crop", output_html),
                existing_link(operation_crop, "operation crop", output_html),
                optional_link(identity_aid, "identity aid", output_html),
                existing_link(compare, "compare", output_html),
                existing_link(focused, "focused", output_html),
                existing_link(top, "top split", output_html),
                existing_link(bottom, "bottom split", output_html),
                existing_link(guide, "box guide", output_html),
            ]
            + preview_links(review_dir, sample, output_html)
        )
        links = " | ".join(link for link in link_items if link)

        cards.append(
            "\n".join(
                [
                    f"<section class='case' id='{html.escape(sample)}'>",
                    "<div class='case-head'>",
                    f"<h2>{sample} <span>#{sample_num}</span></h2>",
                    f"<strong>{html.escape(row.get('current_status', ''))}</strong>",
                    "</div>",
                    f"<p class='task'>{html.escape(row.get('task_text', ''))}</p>",
                    "<dl>",
                    f"<dt>Issue frames</dt><dd>{html.escape(row.get('issue_frames', ''))}</dd>",
                    f"<dt>Reason</dt><dd>{html.escape(row.get('reasons', ''))}</dd>",
                    f"<dt>Decision needed</dt><dd>{html.escape(rec.get('decision', ''))}</dd>",
                    f"<dt>Default recommendation</dt><dd>{html.escape(rec.get('default', ''))}</dd>",
                    "</dl>",
                    f"<p class='links'>{links}</p>",
                    image_block(issue_crop, f"{sample} issue crop", output_html),
                    "</section>",
                ]
            )
        )

    top_links = " | ".join(
        [
            existing_link(summary_dir / "sam3_mask_review_dashboard.html", "main dashboard", output_html),
            existing_link(summary_dir / "human_annotation_decisions.md", "decision notes", output_html),
            existing_link(summary_dir / "human_decision_template.csv", "decision csv", output_html),
            existing_link(summary_dir / "run_delta_summary.md", "run delta", output_html),
            existing_link(summary_dir / "run_delta_summary.csv", "run delta csv", output_html),
            existing_link(summary_dir / "review_bundle_verification.md", "verification", output_html),
            existing_link(summary_dir / "review_bundle_verification.json", "verification json", output_html),
            existing_link(summary_dir / "issue_frames.csv", "issue frames", output_html),
            existing_link(summary_dir / "review_metrics.csv", "metrics", output_html),
        ]
    )

    html_text = f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>SAM3 Human Decision Pack</title>
  <style>
    body {{
      margin: 0;
      background: #f3f5f7;
      color: #141922;
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
    }}
    header {{
      position: sticky;
      top: 0;
      z-index: 2;
      background: rgba(255, 255, 255, 0.96);
      border-bottom: 1px solid #d8dee8;
      padding: 18px 24px;
    }}
    h1 {{
      margin: 0 0 8px;
      font-size: 28px;
    }}
    .sub {{
      color: #596271;
      margin: 0 0 10px;
      line-height: 1.45;
    }}
    a {{
      color: #1c62d0;
      font-weight: 650;
      text-decoration: none;
    }}
    main {{
      padding: 22px 24px 72px;
      display: grid;
      gap: 24px;
    }}
    .case {{
      background: white;
      border: 1px solid #d8dee8;
      border-radius: 10px;
      box-shadow: 0 1px 2px rgba(15, 23, 42, 0.05);
      overflow: hidden;
    }}
    .case-head {{
      display: flex;
      align-items: center;
      justify-content: space-between;
      gap: 16px;
      padding: 18px 20px 8px;
    }}
    h2 {{
      margin: 0;
      font-size: 24px;
    }}
    h2 span {{
      color: #697386;
      font-size: 16px;
      font-weight: 600;
    }}
    strong {{
      border-radius: 999px;
      background: #fff4cc;
      color: #6e5200;
      padding: 6px 10px;
      font-size: 13px;
    }}
    .task {{
      margin: 0;
      padding: 0 20px 12px;
      color: #394150;
      font-size: 15px;
    }}
    dl {{
      display: grid;
      grid-template-columns: 190px minmax(0, 1fr);
      gap: 8px 14px;
      margin: 0;
      padding: 14px 20px;
      border-top: 1px solid #edf0f4;
      border-bottom: 1px solid #edf0f4;
      background: #fbfcfd;
    }}
    dt {{
      color: #697386;
      font-weight: 700;
    }}
    dd {{
      margin: 0;
      color: #1f2937;
    }}
    .links {{
      padding: 12px 20px;
      margin: 0;
      color: #667085;
    }}
    .image-block {{
      margin: 0;
      padding: 0 20px 22px;
    }}
    figcaption {{
      color: #5b6472;
      font-size: 13px;
      font-weight: 700;
      margin-bottom: 8px;
    }}
    img {{
      display: block;
      width: 100%;
      max-height: 82vh;
      object-fit: contain;
      object-position: top left;
      background: #e9edf3;
      border: 1px solid #d8dee8;
    }}
    .missing {{
      color: #b42318;
      font-weight: 700;
    }}
  </style>
</head>
<body>
  <header>
    <h1>SAM3 Human Decision Pack</h1>
    <p class="sub">Focused review for the unresolved operation-mask cases. This is for human QA only; it does not approve full-data mask generation or V3 training by itself.</p>
    <nav>{top_links}</nav>
  </header>
  <main>
    {''.join(cards)}
  </main>
</body>
</html>
"""
    output_html.write_text(html_text, encoding="utf-8")


def main() -> None:
    args = parse_args()
    review_dir = Path(args.review_dir)
    output_html = Path(args.output_html) if args.output_html else review_dir / "summary" / "human_decision_pack.html"
    output_csv = Path(args.output_csv) if args.output_csv else review_dir / "summary" / "human_decision_template.csv"
    issue_rows = read_csv_rows(review_dir / "summary" / "issue_frames.csv")
    write_decision_csv(issue_rows, output_csv)
    write_html(review_dir, issue_rows, output_html, args.detail_label)
    print(output_html.resolve())
    print(output_csv.resolve())


if __name__ == "__main__":
    main()
